apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coolcert
  labels:
    app.kubernetes.io/name: coolcert
    app.kubernetes.io/component: api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: coolcert
      app.kubernetes.io/component: api
