apiVersion: v1
kind: Service
metadata:
  name: coolcert
  labels:
    app.kubernetes.io/name: coolcert
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: coolcert
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
