apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coolcert-prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: coolcert
    newName: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/coolcert
    newTag: local

patches:
  - target:
      kind: Ingress
      name: coolcert
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - coolcert-api.babbage.systems
      - op: replace
        path: /spec/rules
        value:
          - host: coolcert-api.babbage.systems
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: coolcert
                      port:
                        number: 8080
  - target:
      kind: Certificate
      name: coolcert-tls
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - coolcert-api.babbage.systems
